apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.name }}
  ports:
    - port: 80
      targetPort: 80
