apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Values.name }}"
data:
  base.json: {{ .Values.config.base | quote }}
  app.json: {{ .Values.config.app | quote }}
