apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.name}}
  annotations:
  {{- if .Values.prometheus.monitor.enabled}}
    prometheus.io/scrape: "true"
  {{- end}}
  {{- if .Values.service.annotations }}
    {{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
  labels: {{ toYaml .Values.service.labels | indent 4 }}
spec:
  selector:
    app: {{.Values.name}}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if ( and (eq .Values.service.type "NodePort" ) (not (empty .Values.service.nodePort)) ) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: metrics
