name: ops

env:
  default:
    NAME: "ops"
    IMAGE_TAG: "$(git describe --tags | awk '{print(substr($0,2,length($0)))}'; test ${PIPESTATUS[0]} -eq 0)"
  aliyun:
    REGISTRY_ENDPOINT: "{{.registry.aliyun.endpoint}}"
    REGISTRY_USERNAME: "{{.registry.aliyun.username}}"
    REGISTRY_PASSWORD: "{{.registry.aliyun.password}}"
    REGISTRY_NAMESPACE: "{{.registry.aliyun.namespace}}"
  docker:
    REGISTRY_ENDPOINT: "{{.registry.docker.endpoint}}"
    REGISTRY_USERNAME: "{{.registry.docker.username}}"
    REGISTRY_PASSWORD: "{{.registry.docker.password}}"
    REGISTRY_NAMESPACE: "{{.registry.docker.namespace}}"

task:
  image:
    step:
      - make image
      - docker login --username="${REGISTRY_USERNAME}" --password="${REGISTRY_PASSWORD}" "${REGISTRY_ENDPOINT}"
      - docker push "${REGISTRY_ENDPOINT}/${REGISTRY_NAMESPACE}/${NAME}:${IMAGE_TAG}"
