name: myapp

replicaCount: 1
image:
  repository: nginx
  tag: 1.0.0
  pullPolicy: Always
  pullSecret: pull-secret

nodeAffinity:
  enable: false
  key: test.io/app-name
  val: myapp

podAntiAffinity:
  enable: true
tolerations:
  enable: false
  key: dedicated
  val: myapp

container:
  port: 80
  runAsRoot: false
  configMountPath:

ingress:
  enable: false
  host: hatlonely.com
  secretName: test-secret

config:
  base: "{}"
  app: "{}"