namespace: prod
name: myapp
replicaCount: 1

image:
  repository: registry.cn-beijing.aliyuncs.com/hatlonely/myapp
  tag: 1.0.0
  pullPolicy: Always
  pullSecret: hatlonely-pull-secrets

container:
  runAsRoot: false

nodeAffinity:
  enable: false
  key: test.io/app-name
  val: myapp

podAntiAffinity:
  enable: false

tolerations:
  enable: false
  key: dedicated
  val: myapp

ingress:
  enable: false
  host: k8s.myapp.hatlonely.com
  secretName: k8s-secret

config:
  base: "{}"
  app: "{}"