namespace: prod
name: myapp
replicaCount: 1

image:
  repository: registry.cn-beijing.aliyuncs.com/hatlonely/myapp
  tag: 1.0.0
  pullPolicy: Always
  pullSecret: hatlonely-pull-secrets

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  labels: {}
  portName: service
  annotations: {}

container:
  runAsRoot: false

nodeAffinity:
  enable: false
  key: test.io/app-name
  val: myapp

podAntiAffinity:
  enable: false

tolerations:
  enable: false
  key: dedicated
  val: myapp

ingress:
  enable: false
  host: k8s.myapp.hatlonely.com
  secretName: k8s-secret

prometheus:
  monitor:
    enabled: false
    additionalLabels: {}
    namespace: ""
    scheme: http
    path: /metrics
    bearerTokenFile:
    tlsConfig: {}
    relabelings: []
    scrapeTimeout: 10s

config:
  base: "{}"
  app: "{}"