{{- if .Values.prometheus.monitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.name}}
  labels: {{ toYaml .Values.service.labels | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
      release: {{ .Release.Name }}
  endpoints:
    - port: metrics
      path: {{ .Values.prometheus.monitor.path }}
      scheme: {{ .Values.prometheus.monitor.scheme }}
      {{- if .Values.prometheus.monitor.bearerTokenFile }}
      bearerTokenFile: {{ .Values.prometheus.monitor.bearerTokenFile }}
      {{- end }}
      {{- if .Values.prometheus.monitor.tlsConfig }}
      tlsConfig: {{ toYaml .Values.prometheus.monitor.tlsConfig | nindent 8 }}
      {{- end }}
      {{- if .Values.prometheus.monitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.prometheus.monitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.prometheus.monitor.relabelings }}
      relabelings:
        {{ toYaml .Values.prometheus.monitor.relabelings | indent 6 }}
      {{- end }}
{{- end }}